### ISSUE TITLE
Bad set of indicies for elf file...

### ISSUE THREAD

**Issue by kbigliar** [Ridgure/TwitchBot#1]
https://github.com/Ridgure/TwitchBot/blob/313f8231600da1b7549df406106e68569b6f2fe4/bot.py#L1389

instead of indexing every value, do something like

 for i2 in [8,10,12,14,16,18]:

or possibly (for future scalability)

firstNames = []
index = 8
while index  < range(len(subscriberLines[i1])):
     firstNames.append(index)
     index += 2
for i2 in firstNames

**Comment by Ridgure** [comment]
Interesting. Will check this out.

**Comment by Ridgure** [comment]
Have changed to suggested as in line 2:

for i2 in [8,10,12,14,16,18]:

Works for now until infinite elfs break it again in which case I will have to come back here for inspiration. Never added so much information into a for loop parameter. Interesting.

**Comment by kbigliar** [comment]
the bottom one will populate every other index starting at the specified first index given up til the last elf is named.

**Comment by Ridgure** [comment]
Elves are now set do populate infinitely
