### ISSUE TITLE
probable speedup

### ISSUE THREAD

**Issue by kbigliar** [Ridgure/TwitchBot#10]
one probable speedup would be to save `text.lower().split()[0]` to a var instead of performing 2 functions on every command check

so like `firstStr = text.lower().split()[0]` and replace all instances of text.lower().split()[0] with firstStr

**Comment by kbigliar** [comment]
while going through all the commands, change all but the first if to elif ... else 

> !uptime!commands!bugs

would run 3 commands at once... just as one example.

**Comment by kbigliar** [comment]
Just thought of this extra addition. Maybe have a check to see if '!' appears in the first word before checking against all the possible commands.

**Comment by Ridgure** [comment]
All three speedups have been implemented
