### ISSUE TITLE
Fun chat failure...

### ISSUE THREAD

**Issue by kbigliar** [Ridgure/TwitchBot#14]
It is fixed, but this block referenced the title line of the cvs file by mistake making the int() function fail to parse properly, causing the file to not save, causing the thx for sub msgs to reappear in chat... on... every... message.... YIKES!!! https://github.com/Ridgure/TwitchBot/blob/556577a69bbe0b76d5f4d96db559fd321670aa2e/bot.py#L764-L819

**Comment by Ridgure** [comment]
Fixed this issue by skipping the first line in subscriber.csv on two places
