### ISSUE TITLE
 Error code 404 for link in ReadMe 

### ISSUE THREAD

**Issue by DylanClarkOffical** [Ridgure/TwitchBot#22]
this link in (https://github.com/Ridgure/TwitchBot/edit/master/README.md) under prerequisites no longer works 
https://pypi.org/project/TinyUrl/

**Comment by Ridgure** [comment]
Tinyurl has been discontinued but I still have the library.
Will distribute myself instead. The link has been updated.
Issue has been resolved.
Thank you for your contribution
