### ISSUE TITLE
a way to cut off 110 lines of code.

### ISSUE THREAD

**Issue by kbigliar** [Ridgure/TwitchBot#7]
https://github.com/Ridgure/TwitchBot/blob/2a86f6d00961933ec8aeb052e79d4de6b10607d9/bot.py#L790-L965

do this instead to save lines...

https://pastebin.com/eBYaPsJ2

**Comment by Ridgure** [comment]
This is so genius!

**Comment by Ridgure** [comment]
These lines have been condensed
